name = "therml_environment"
uuid = "8e61acd7-0f6c-43fe-a596-41f12fca9848"
authors = ["Aniket <ani.kulkar@gmail.com>"]
version = "0.1.0"

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
DifferentialEquations = "0c46a032-eb83-5123-abaf-570d42b7fbaa"
HDF5 = "f67ccb44-e63f-5c2f-98bd-6dc0ccc4ba2f"
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
LoggingExtras = "e6f89c97-d47a-5376-807f-9c37f3926c36"
LoopVectorization = "bdcacae8-1622-11e9-2a5c-532679323890"
Nettle = "49dea1ee-f6fa-5aa6-9a11-8816cee7d4b9"
PlotlyJS = "f0f68f2c-4968-5e81-91da-67840de0976a"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
Sundials = "c3572dad-4567-51f8-b174-8c6c989267f4"
Symbolics = "0c5d862f-8b57-4792-8d23-62f2024744c7"
TerminalLoggers = "5d786b92-1e48-4d6f-9151-6b4477ca9bed"
Tullio = "bc48ee85-29a4-5162-ae0b-a64e1601d4bc"
